# Generated by Django 6.0.6 on 2026-06-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('author', models.CharField(max_length=2000)),
                ('price', models.CharField(max_length=2000)),
                ('description', models.CharField(max_length=3000)),
                ('address', models.CharField(max_length=2000)),
                ('is_published', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
    ]
