# Generated by Django 6.0.6 on 2026-06-21 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 6, 21, 17, 20, 16, 514824, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='categories',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('open', 'Открыто'), ('closed', 'Закрыто')], default='draft', max_length=6),
        ),
    ]
